### ISSUE TITLE
Repo Maintainence Roadmap

### ISSUE THREAD

**Issue by austinkelleher** [mlrawlings/it-fails#1]
I look forward to maintaining this repo. I assigned this issue to both of us to track our own progress here. We can track all sorts of stuff here. That's the beauty of GitHub.

**Comment by ctdio** [comment]
Thanks for creating this issue @austinkelleher. I look forward to seeing progress being tracked here.

There seems to be a distinct lack of 10xers working on this repo though. /cc @DylanPiercey

**Comment by mlrawlings** [comment]
To commemorate you being a maintainer, I propose we rename this project to `austin-kelleher-fails`.

**Comment by mlrawlings** [comment]
Also, @charlieduong94 I added you as a maintainer as well.  I look forward to your contributions.

**Comment by ctdio** [comment]
I'm honored @mlrawlings, I won't let you down.

**Comment by DylanPiercey** [comment]
He needs to be let down @charlieduong94, the power of repo owner is getting to him.
Relevant link: https://help.github.com/articles/reporting-abuse-or-spam/

**Comment by ctdio** [comment]
Having @austinkelleher as a maintainer should be enough to do that.

**Comment by austinkelleher** [comment]
Closing because I don't use this module anymore. Sorry not sorry.
